from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from types import ModuleType
from typing import TypeVar

import numpy as np
import torch
from numpy.typing import NDArray

from array_api_compat import array_namespace

ArrayLike = TypeVar("ArrayLike", torch.Tensor, NDArray)

TWO_PI = 2 * np.pi


def level_dtype(bitdepth: int, xp: ModuleType = np):
    """The smallest integer type that holds a level of this depth."""
    return xp.uint8 if int(bitdepth) <= 8 else xp.uint16


class PhaseResponse(ABC):
    """Gray level to phase response of the SLM. ``phase_scaling`` is the phase the 
    SLM can reach in cycles.
    """

    bitdepth: int

    @property
    @abstractmethod
    def phase_scaling(self) -> float:
        """The reachable phase range, in cycles."""

    @abstractmethod
    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        """The phase generated by a fraction of full scale."""

    @abstractmethod
    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        """The fraction of full scale resulting in ``phase``, the continuous inverse."""

    @property
    def number_of_levels(self) -> int:
        return 2 ** int(self.bitdepth)

    def to_phase(self, levels: ArrayLike) -> ArrayLike:
        """The phase generated by ``levels``."""
        return self.phase_at(_as_float(levels) / self.number_of_levels)

    def to_levels(self, phase: ArrayLike) -> ArrayLike:
        """The levels resulting in ``phase``."""
        return self.fraction_at(phase) * self.number_of_levels

    def round_to_levels(self, levels: ArrayLike) -> ArrayLike:
        xp = array_namespace(levels)
        return xp.round(levels) % self.number_of_levels

    def display_levels(self, phase: ArrayLike) -> ArrayLike:
        """The integer levels that result in ``phase``, ready for an SLM to display."""
        levels = self.round_to_levels(self.to_levels(phase))
        xp = array_namespace(levels)
        return xp.astype(levels, level_dtype(self.bitdepth, xp))

    def wrap_fraction(self, fraction: ArrayLike) -> ArrayLike:
        """The fraction of full scale the SLM shows when asked for ``fraction``."""
        return self.fraction_at(self.phase_at(fraction))


@dataclass(frozen=True)
class LinearResponse(PhaseResponse):
    """A straight line from zero at level zero to ``phase_scaling`` cycles at full
    scale.
    """

    bitdepth: int
    phase_scaling: float = 1.0

    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        return -_as_float(fraction) * self.phase_scaling * TWO_PI

    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        xp = array_namespace(phase)
        cycles = (-_as_float(phase) / TWO_PI) % 1.0
        fraction = cycles / self.phase_scaling
        if self.phase_scaling >= 1.0:
            return fraction
        # Beyond full scale there is no level to ask for, so hold at the last one.
        return xp.clip(fraction, 0.0, 1.0 - 1.0 / self.number_of_levels)


@dataclass(frozen=True)
class LookupResponse(PhaseResponse):
    """Phase response described by a measured curve, one phase per level.

    Args:
        bitdepth: Bits per pixel, so the table has ``2**bitdepth`` entries.
        phases: The phase each level generates, in radians, monotone and starting at
            zero. Can be a vendor lookup table, or a measurement.
    """

    bitdepth: int
    phases: NDArray = field(default_factory=lambda: np.zeros(0))

    @property
    def phase_scaling(self) -> float:
        """Read off the lookup table."""
        return float((self.phases[0] - self.phases[-1]) / TWO_PI)

    def __post_init__(self) -> None:
        phases = np.asarray(self.phases, dtype=np.float64)
        if phases.shape != (self.number_of_levels,):
            raise ValueError(
                f"A {self.bitdepth}-bit response needs {self.number_of_levels} phases, "
                f"got {phases.shape}."
            )
        differences = np.diff(phases)
        if np.any(differences > 0) and np.any(differences < 0):
            raise ValueError(
                "The response must be monotone, so a phase maps back to one level. "
                "This table rises and falls."
            )

    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        position = _as_float(fraction) * self.number_of_levels
        return _interpolate(_table(self.phases, position), position)

    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        phase = _as_float(phase)
        table = _table(self.phases, phase)
        # The table runs downhill from zero, so search it the other way up.
        rising = -table
        wanted = -_wrap_into_span(phase, table)
        return _invert(rising, wanted) / self.number_of_levels


class PhaseResponseModule(torch.nn.Module):
    """A learnable :class:`PhaseResponse`."""

    def __init__(self, response: PhaseResponse) -> None:
        super().__init__()
        self.response = response
        if isinstance(response, LookupResponse):
            self.register_buffer(
                "table", torch.as_tensor(response.phases, dtype=torch.float64)
            )

    @property
    def bitdepth(self) -> int:
        return self.response.bitdepth

    @property
    def phase_scaling(self) -> float:
        return self.response.phase_scaling

    @property
    def number_of_levels(self) -> int:
        return self.response.number_of_levels

    def phase_at(self, fraction: torch.Tensor) -> torch.Tensor:
        return self.response.phase_at(fraction)

    def fraction_at(self, phase: torch.Tensor) -> torch.Tensor:
        return self.response.fraction_at(phase)

    def to_phase(self, levels: torch.Tensor) -> torch.Tensor:
        return self.response.to_phase(levels)

    def to_levels(self, phase: torch.Tensor) -> torch.Tensor:
        return self.response.to_levels(phase)

    def wrap_fraction(self, fraction: torch.Tensor) -> torch.Tensor:
        return self.response.wrap_fraction(fraction)

    def quantize(self, levels: torch.Tensor) -> torch.Tensor:
        """Round to whole levels, leaving the gradient unchanged (straight-through
        estimator).
        """
        whole = self.response.round_to_levels(levels)
        return levels + (whole - levels).detach()


def _as_float(array: ArrayLike) -> ArrayLike:
    """Levels arrive as integers, which have to leave the integers to be scaled."""
    xp = array_namespace(array)
    if xp.isdtype(array.dtype, "real floating"):
        return array
    return xp.astype(array, xp.float64)


def _table(phases: NDArray, like: ArrayLike) -> ArrayLike:
    """The stored table as the kind and precision of array the caller is working in."""
    if isinstance(like, torch.Tensor):
        return torch.as_tensor(phases, dtype=like.dtype, device=like.device)
    return np.asarray(phases, dtype=like.dtype)


def _interpolate(table: ArrayLike, position: ArrayLike) -> ArrayLike:
    """The table read at a fractional index, linearly between its entries."""
    xp = array_namespace(table)
    last = table.shape[0] - 1
    lower = xp.clip(xp.astype(xp.floor(position), xp.int64), 0, last)
    upper = xp.clip(lower + 1, 0, last)
    weight = xp.clip(position - _as_float(lower), 0.0, 1.0)
    return table[lower] + weight * (table[upper] - table[lower])


def _invert(rising: ArrayLike, wanted: ArrayLike) -> ArrayLike:
    """Where ``wanted`` sits in a rising table, as a fractional index."""
    xp = array_namespace(rising)
    if isinstance(wanted, torch.Tensor):
        index = torch.searchsorted(
            rising.contiguous(), wanted.reshape(-1).contiguous()
        ).reshape(wanted.shape)
    else:
        index = np.searchsorted(rising, wanted)

    last = rising.shape[0] - 1
    upper = xp.clip(index, 1, last)
    lower = upper - 1
    step = rising[upper] - rising[lower]
    # A flat step is a level the SLM repeats, where any of them will do.
    safe = xp.where(step == 0, xp.ones_like(step), step)
    weight = xp.where(step == 0, xp.zeros_like(step), (wanted - rising[lower]) / safe)
    return _as_float(lower) + weight


def _wrap_into_span(phase: ArrayLike, table: ArrayLike) -> ArrayLike:
    """A desired phase brought into the range the table covers."""
    xp = array_namespace(phase)
    top, bottom = table[0], table[-1]
    span = top - bottom
    wrapped = top - ((top - phase) % TWO_PI)
    return xp.where(span >= TWO_PI, wrapped, xp.clip(phase, bottom, top))
