from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from types import ModuleType
from typing import TypeVar

import numpy as np
import torch
from numpy.typing import NDArray

from array_api_compat import array_namespace

ArrayLike = TypeVar("ArrayLike", torch.Tensor, NDArray)

TWO_PI = 2 * np.pi


def level_dtype(
    bitdepth: int, xp: ModuleType = np
) -> type[np.unsignedinteger] | torch.dtype:
    """The smallest integer type that holds a level of this depth."""
    return xp.uint8 if int(bitdepth) <= 8 else xp.uint16


class PhaseResponse(ABC):
    """Gray level to phase response of an SLM.

    The phase decreases with increasing level. Full scale is level ``2**bitdepth``, one
    past the last level, and ``full_scale_cycles`` is the phase delay there, in cycles.
    """

    bitdepth: int

    @property
    @abstractmethod
    def full_scale_cycles(self) -> float:
        """The phase delay at full scale, level ``2**bitdepth``, in cycles."""

    @abstractmethod
    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        """The phase generated by a fraction of full scale. Past full scale the curve
        repeats, shifted by the phase at full scale on each repeat.
        """

    @abstractmethod
    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        """The fraction of full scale resulting in ``phase``, the continuous inverse.

        The phase is wrapped into one cycle first. A response short of a full cycle
        clips a phase delay no level reaches to the delay of the last level.
        """

    @property
    def number_of_levels(self) -> int:
        return 2 ** int(self.bitdepth)

    def to_phase(self, levels: ArrayLike) -> ArrayLike:
        """The phase generated by ``levels``."""
        return self.phase_at(_as_float(levels) / self.number_of_levels)

    def to_levels(self, phase: ArrayLike) -> ArrayLike:
        """The levels resulting in ``phase``."""
        return self.fraction_at(phase) * self.number_of_levels

    def round_to_levels(self, levels: ArrayLike) -> ArrayLike:
        """Whole levels, wrapped into the range the SLM can display."""
        xp = array_namespace(levels)
        return xp.round(_as_float(levels)) % self.number_of_levels

    def display_levels(self, phase: ArrayLike) -> ArrayLike:
        """The integer levels that result in ``phase``, ready for an SLM to display."""
        levels = self.round_to_levels(self.to_levels(phase))
        xp = array_namespace(levels)
        return xp.astype(levels, level_dtype(self.bitdepth, xp))

    def wrap_fraction(self, fraction: ArrayLike) -> ArrayLike:
        """The fraction of full scale the SLM shows when asked for ``fraction``."""
        return self.fraction_at(self.phase_at(fraction))


@dataclass(frozen=True)
class LinearResponse(PhaseResponse):
    """A straight line from zero at level zero to ``full_scale_cycles`` cycles at full
    scale.
    """

    bitdepth: int
    full_scale_cycles: float = 1.0

    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        return -_as_float(fraction) * self.full_scale_cycles * TWO_PI

    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        cycles = (-_as_float(phase) / TWO_PI) % 1.0
        fraction = cycles / self.full_scale_cycles
        if self.full_scale_cycles >= 1.0:
            return fraction
        xp = array_namespace(fraction)
        return xp.clip(fraction, 0.0, 1.0 - 1.0 / self.number_of_levels)


@dataclass(frozen=True, eq=False)
class LookupResponse(PhaseResponse):
    """Phase response described by a table, one phase per level.

    Args:
        bitdepth: Bits per pixel, so the table has ``2**bitdepth`` entries.
        phases: The phase each level generates, in radians, monotone and falling with
            level.
    """

    bitdepth: int
    phases: NDArray = field(default_factory=lambda: np.zeros(0))

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "phases", _normalized_table(self.phases, self.bitdepth)
        )

    @classmethod
    def from_phase_delays(
        cls, bitdepth: int, delays: NDArray | torch.Tensor
    ) -> LookupResponse:
        """A response from the phase delay each level adds, the form a vendor table or
        a measurement takes.

        A delay rises with level, and the phase this package displays is its negative.

        Args:
            bitdepth: Bits per pixel, so the table has ``2**bitdepth`` entries.
            delays: The phase delay each level adds, in radians, rising with level.

        Returns:
            LookupResponse: The response whose phase at each level is minus its delay.
        """
        if torch.is_tensor(delays):
            delays = delays.detach().cpu().numpy()
        return cls(bitdepth=bitdepth, phases=-np.asarray(delays, dtype=np.float64))

    @property
    def full_scale_cycles(self) -> float:
        """The phase delay at full scale in cycles, the table's mean step carried one
        level past its last entry.
        """
        levels = self.number_of_levels
        return float(-self.phases[-1] * levels / (levels - 1) / TWO_PI)

    @property
    def _phases_through_full_scale(self) -> NDArray:
        """The table with the phase at full scale appended, one entry per level up to
        and including ``2**bitdepth``.
        """
        return np.append(self.phases, -self.full_scale_cycles * TWO_PI)

    def phase_at(self, fraction: ArrayLike) -> ArrayLike:
        levels = self.number_of_levels
        position = _as_float(fraction) * levels
        xp = array_namespace(position)
        # Past full scale the curve repeats, shifted by the phase at full scale on each
        # repeat, as the line of LinearResponse continues.
        repeats = xp.floor(position / levels)
        within = position - repeats * levels
        table = _table(self._phases_through_full_scale, within)
        return _interpolate(table, within) - repeats * (self.full_scale_cycles * TWO_PI)

    def fraction_at(self, phase: ArrayLike) -> ArrayLike:
        phase = _as_float(phase)
        levels = self.number_of_levels
        # The table falls from zero, so its negative is a delay, which rises.
        delays = -_table(self._phases_through_full_scale, phase)
        wanted = (-phase) % TWO_PI
        fraction = _invert(delays, wanted) / levels
        if self.full_scale_cycles >= 1.0:
            return fraction
        xp = array_namespace(fraction)
        return xp.clip(fraction, 0.0, 1.0 - 1.0 / levels)


class PhaseResponseModule(torch.nn.Module):
    """A :class:`PhaseResponse` held by a torch module. A lookup table is also
    registered as the buffer ``table``, so a state dict carries it. The conversions
    read the response itself.
    """

    def __init__(self, response: PhaseResponse) -> None:
        super().__init__()
        self.response = response
        if isinstance(response, LookupResponse):
            self.register_buffer(
                "table", torch.tensor(response.phases, dtype=torch.float64)
            )

    @property
    def bitdepth(self) -> int:
        return self.response.bitdepth

    @property
    def full_scale_cycles(self) -> float:
        return self.response.full_scale_cycles

    @property
    def number_of_levels(self) -> int:
        return self.response.number_of_levels

    def phase_at(self, fraction: torch.Tensor) -> torch.Tensor:
        return self.response.phase_at(fraction)

    def fraction_at(self, phase: torch.Tensor) -> torch.Tensor:
        return self.response.fraction_at(phase)

    def to_phase(self, levels: torch.Tensor) -> torch.Tensor:
        return self.response.to_phase(levels)

    def to_levels(self, phase: torch.Tensor) -> torch.Tensor:
        return self.response.to_levels(phase)

    def wrap_fraction(self, fraction: torch.Tensor) -> torch.Tensor:
        return self.response.wrap_fraction(fraction)

    def quantize(self, levels: torch.Tensor) -> torch.Tensor:
        """Round to whole levels, leaving the gradient unchanged (straight-through
        estimator).
        """
        whole = self.response.round_to_levels(levels)
        return levels + (whole - levels).detach()


def _normalized_table(phases: NDArray | torch.Tensor, bitdepth: int) -> NDArray:
    """The table as a read-only float64 copy, shifted so level zero holds zero.

    Args:
        phases: The phase each level generates, in radians.
        bitdepth: Bits per pixel, so the table needs ``2**bitdepth`` entries.

    Returns:
        NDArray: The shifted, read-only copy.

    Raises:
        ValueError: The table has the wrong length, holds a NaN or infinite phase,
            rises and falls, holds one phase at every level, or rises with level.
    """
    if torch.is_tensor(phases):
        phases = phases.detach().cpu().numpy()
    table = np.array(phases, dtype=np.float64)
    number_of_levels = 2 ** int(bitdepth)
    if table.shape != (number_of_levels,):
        raise ValueError(
            f"A {bitdepth}-bit response needs {number_of_levels} phases, "
            f"got {table.shape}."
        )
    if not np.all(np.isfinite(table)):
        raise ValueError(
            "The table holds a NaN or infinite phase, so that level has no phase to "
            "invert to."
        )
    # Level zero is the reference, as in LinearResponse.
    table = table - table[0]
    steps = np.diff(table)
    if np.any(steps > 0) and np.any(steps < 0):
        raise ValueError(
            "The response must be monotone, so a phase maps back to one level. This "
            "table rises and falls. Unwrap a measured table with numpy.unwrap, then "
            "smooth or fit it until no step goes against the others."
        )
    if not np.any(steps):
        raise ValueError(
            "Every level of this table holds the same phase, so no level changes the "
            "phase."
        )
    if not np.any(steps < 0):
        raise ValueError(
            "This table rises with level. In this package the phase falls with level, "
            "the sign LinearResponse and slmsuite use. A vendor table or a measured "
            "delay rises, and LookupResponse.from_phase_delays takes it."
        )
    table.flags.writeable = False
    return table


def _as_float(array: ArrayLike) -> ArrayLike:
    """Levels arrive as integers, which have to leave the integers to be scaled."""
    xp = array_namespace(array)
    if xp.isdtype(array.dtype, "real floating"):
        return array
    return xp.astype(array, xp.float64)


def _table(phases: NDArray, like: ArrayLike) -> ArrayLike:
    """The stored table as the kind and precision of array the caller is working in."""
    if isinstance(like, torch.Tensor):
        return torch.as_tensor(phases, dtype=like.dtype, device=like.device)
    return np.asarray(phases, dtype=like.dtype)


def _interpolate(table: ArrayLike, position: ArrayLike) -> ArrayLike:
    """The table read at a fractional index, linearly between its entries."""
    xp = array_namespace(table)
    last = table.shape[0] - 1
    lower = xp.clip(xp.astype(xp.floor(position), xp.int64), 0, last)
    upper = xp.clip(lower + 1, 0, last)
    weight = xp.clip(position - _as_float(lower), 0.0, 1.0)
    return table[lower] + weight * (table[upper] - table[lower])


def _invert(rising: ArrayLike, wanted: ArrayLike) -> ArrayLike:
    """Where ``wanted`` sits in a rising table, as a fractional index."""
    xp = array_namespace(rising)
    if isinstance(wanted, torch.Tensor):
        index = torch.searchsorted(
            rising.contiguous(), wanted.reshape(-1).contiguous()
        ).reshape(wanted.shape)
    else:
        index = np.searchsorted(rising, wanted)

    last = rising.shape[0] - 1
    upper = xp.clip(index, 1, last)
    lower = upper - 1
    step = rising[upper] - rising[lower]
    # A flat step is a level the SLM repeats, where any of them will do.
    safe = xp.where(step == 0, xp.ones_like(step), step)
    weight = xp.where(step == 0, xp.zeros_like(step), (wanted - rising[lower]) / safe)
    return _as_float(lower) + weight
